### ISSUE TITLE
Terminate dialog overflows

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui#1045]
**Describe the bug**

![image](https://user-images.githubusercontent.com/251288/211951139-d34615b2-0b68-413c-837d-09d4f9020d28.png)

Version of the UI shipped with `temporal` version 0.2.0

**Comment by Alex-Tideman** [comment]
Hey Loren, this is already fixed in 2.9.1 which is deployed. 

It's helped if the screenshot includes the ui-server version number in the bottom of the nav so we can if it's already fixed.

<img width="1728" alt="Screen Shot 2023-01-11 at 7 42 10 PM" src="https://user-images.githubusercontent.com/7967403/211955904-b0f5160d-b18e-4f6d-aae8-b011fa6195b3.png">

**Comment by lorensr** [comment]
Ah I see it, thanks!
