### ISSUE TITLE
Cannot select (to copy/paste) any text in table

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#284]
<img width="1498" alt="Screen Shot 2022-03-07 at 11 51 32 AM" src="https://user-images.githubusercontent.com/119422/157080232-69fb2c11-b0ac-4def-b89e-46fc88fbf3ed.png">

Its not possible to select any text here to copy. It's useful to do that so you can copy a workflow type or id so can paste it in the search boxes above for filtering

**Comment by stevekinney** [comment]
@canvanooo We talked about putting copy icons in this view right? The issue is caused by the entire row being a link (and thereby allowing you to click anywhere to see the workflow). This choice pre-dates you, but I think it's the right call.

Also: We _could_ add a button that automatically populates the filter, since that's probably the reason why the user is copying the type or ID, right?

**Comment by canvanooo** [comment]
@stevekinney I started working the copy icons into the workflow details page. Let's see if we can right click and copy row items on the workflow list page, that should be a good help. 

I like your idea of populating filters, that's neat. I'll mock that up.

**Comment by stevekinney** [comment]
I think we can close this one for now as you're presently able to select the text in the table rows. We've got the copy buttons tracked as a separate feature request.
