### ISSUE TITLE
Clicking on "Stack Trace" on a completed workflow does nothing

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#291]
<img width="543" alt="Screen Shot 2022-03-07 at 12 11 11 PM" src="https://user-images.githubusercontent.com/119422/157083512-d62246b7-8e42-4b2b-a7b6-d9962f109b5e.png">

trying to click on "Stack Trace" it does not change the blue underline to see that it did anything
could be some indicator that there is no stack trace for a closed workflow exec

**Comment by stevekinney** [comment]
I was able to reproduce this bug. The issue is when the worker is no longer running, the request to the API stalls as it waits before eventually erroring out.

**Proposed solution**:

- [ ] We should remove the API call from the load function and do it after the initial page loads (We can do this ASAP.)
- [ ] @canvanooo will design a state for when we're polling to see if we have a worker that can get us a stack trace or query.
- [ ] @canvanooo will design a error state for case where we get a 504 because there is no worker.
- [ ] We will implement the aforementioned designs.

**Comment by stevekinney** [comment]
Just a heads up to whoever fixes (probably future me) that this also affects the Query tab as well for the same reason as noted in #308.
