### ISSUE TITLE
[0.4.0] Allow to select namespace

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#318]
If you have multiple namespaces, for example:

<img width="394" alt="Screen Shot 2022-03-14 at 10 22 26 PM" src="https://user-images.githubusercontent.com/119422/158293264-e6dbe5bf-e759-4b4c-a9cf-a4f4bc310221.png">

http://localhost:8080/ and http://localhost:8080/namespaces go directly to "default", in "old" ui there was a way to select it first:

<img width="1347" alt="Screen Shot 2022-03-14 at 10 24 01 PM" src="https://user-images.githubusercontent.com/119422/158293387-645a521e-ed56-4190-af72-61c820f2e973.png">
 
at which point "mynamespace" would become "sticky"

**Comment by tsurdilo** [comment]
To reproduce you can just run tctl command:

tctl -ns mynamespace  namespace register

and then go to web ui

**Comment by canvanooo** [comment]
Ah to set your default namespace, got it. Thank you.

**Comment by feedmeapples** [comment]
currently UI v2 navigates to a default namespace, which can be anything set through config https://github.com/temporalio/ui-server/blob/7c023b211dec324848f49a49cb84fce9e8fc7251/config/development.yaml#L7

the ask seems to be
* if i navigated to a different namespace, for example `accounting`
* next time i open http://localhost:8080/ , it should navigate to accounting instead of default namespace ?

**Comment by feedmeapples** [comment]
idk if we want a separate page for the namespace. If so, we need the design for that

Otherwise, if we stick to the dropdown, one improvement to it could be making the namespaces sticky https://github.com/temporalio/ui/issues/316

Another improvement could be making the namespace dropdown an `input dropdown` to filter namespaces
