### ISSUE TITLE
[0.4.0] Usability - Constant scrolling 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#344]
Every time you click on an event in history the page jumps to the top. For larger histories this requires constant scrolling and its super easy to just lose tack of what you are doing, recording below to show this experience

https://user-images.githubusercontent.com/119422/158630207-fb4c1b6c-9871-4441-a4bf-90c6804e752b.mp4

Imo the v1 experience with properties always being next to the event is much more user friendly, its more continuous and easier when debugging your workflows (again only imo :) )

**Comment by stevekinney** [comment]
Interest fact for anyone (probably future me) who works on this: It doesn't happen in Safari.

**Comment by stevekinney** [comment]
Quick updates: #365 and #366 were attempts to address this issue that didn't do the trick. It's reloading all of the API data as well for these views.

**Comment by feedmeapples** [comment]
Since we don't have the left panel anymore, i don't reproduce this issue with the new view (expanding and collapsing items, clicking on them etc)

![image](https://user-images.githubusercontent.com/11838981/162510166-2d1d3700-9984-463f-8ec9-0d80182676bc.png)

@tsurdilo seem we can close then? Please verify on v0.9.0+
