### ISSUE TITLE
Archival throws error with S3 driver 

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui#572]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11838981/204728083-b3e3c3a6-fc3d-472c-899f-81661bf90194.png)

https://community.temporal.io/t/temporal-ui-beta-version-v2-local-setup/4376/3?u=ruslan

**To Reproduce**

1. Setup archival with s3 backend https://docs.temporal.io/clusters/how-to-set-up-archival/
2. go to Archival tab in the UI

**Expected behavior**

Archival should list workflows with S3 backend

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by alienscavenger** [comment]
@feedmeapples Hi, are there any updates on this issue?

**Comment by xiluoduyu** [comment]
I also encountered this problem.  My solution is to add a proxy to change the query param.

**Comment by alienscavenger** [comment]
@xiluoduyu Sure, that kind of work. But most of the web ui features just straight up does not work because of s3 backend limitation and different query parameters. Even the advanced search also doesn't work.

**Comment by ebennett-fevo** [comment]
search for archived workflows on S3 doesn't work at all with UI v2

**Comment by kkcmadhu** [comment]
yes.. i too see this issue...
We love the new ui, but not supporting s3 archival is  deal breaker for me.. I would  love if this get fixed asap.

The old ui advanced search does a decent job with s3 archival..

**Comment by mfractal** [comment]
Same issue, following.

**Comment by feedmeapples** [comment]
this issue seems getting traction.. i'll check with the team if we can get someone on it (a bit occupied with other non UI items)

**Comment by kkcmadhu** [comment]
> this issue seems getting traction.. i'll check with the team if we can get someone on it (a bit occupied with other non UI items)

Thanks @feedmeapples , is there any update on this

**Comment by kkcmadhu** [comment]
@feedmeapples , This is presently becoming a blocker for us, and i am not able to upgrade temporal to latest version because of this issue. Any way this can be priortized?

**Comment by kkcmadhu** [comment]
Per docs, https://docs.temporal.io/cluster-deployment-guide#archival Local file system is not production grade.
That leaves with S3 and gcp stores out of box..
S3 is breaking in new ui, This really needs to be given due attention i guess.

**Comment by feedmeapples** [comment]
Archival backed by S3 seems to have more limitations compared to filestore. Ex. while i'm seeing filestore archival work fine with the UI, with S3 getting

```

**Comment by feedmeapples** [comment]
@MichaelSnowden is looking into fixing the above error with S3 backed archival

**Comment by kkcmadhu** [comment]
> into fixing the above error with S3 backed archival

Thansk much  @feedmeapples  for followup and getting this priorized! really appricate that!

**Comment by feedmeapples** [comment]
Few updates on the progress, we want to address this in few stages:

1. At the end of the first stage we have 
 - UI filters in archival page disabled as the filters will not currently work with S3 backed Archival
 
 2. As the server team has capacity to get S3 backed Archival on par with the rest of history/visibility filtering options we may enable the UI filters

**Comment by feedmeapples** [comment]
quick update the this item is still in progress, @MichaelSnowden or I will notify here once finished

**Comment by jupudibhaskar967** [comment]
@feedmeapples  Is there any plan to revisit this issue now that server fix is made?

**Comment by feedmeapples** [comment]
this should be working now with the above PR merged and released in v2.14.0

**Comment by kkcmadhu** [comment]
thanks, i just checked this, it works but its far from usable
a) it takes huge time to load the acheives, my archieve runs to few 1000s and it takes a while.
Also it just gets the summar i guess,
clicking on the workflow shows 404,
i think when you click on the archieve search results, it tries to look for the worklow in online/temporal instead of archive this is the url which gets called  "namespaces/<yournamespace>/workflows/<yourworkfllowuuid>/<runid>/history"


I think the old ui was doing much better job as far as archive search is concerned. Not able to understand what broken in between.

**Comment by Balachandar-PE** [comment]
@feedmeapples Does History archival from s3 via UI works with 2.14.0 or in any other versions ?

I'm experiencing the same behaviour as @kkcmadhu in newer versions of UI as well. When opening the workflow id to view history data the UI seems to route to "namespaces/yournamespace/workflows/your-workfllow-name/runid/history" URL, which may not be expected behaviour. Is there a plan to fix this or is there a workaround ?
