### ISSUE TITLE
An error occurred while terminating workflow

### ISSUE THREAD

**Issue by ethink** [temporalio/ui#793]
Hello, I use kubernetes cluster deployment.
I encountered the following problems when deleting workflow.
Curl：curl -X POST "http://114.214.165.1:8080/api/v1/namespaces/default/workflows/recipe_1659424785111/runs/9fdb5f04-ee81-46ac-b8b8-9fd79776ac56/terminate" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"workflowExecution\": { \"workflowId\": \"string\", \"runId\": \"string\" }, \"reason\": \"string\", \"details\": { \"payloads\": [ { \"metadata\": { \"additionalProp1\": \"string\", \"additionalProp2\": \"string\", \"additionalProp3\": \"string\" }, \"data\": \"string\" } ] }, \"identity\": \"string\", \"firstExecutionRunId\": \"string\"}"

Request URL：http://114.214.165.1:8080/api/v1/namespaces/default/workflows/recipe_1659424785111/runs/9fdb5f04-ee81-46ac-b8b8-9fd79776ac56/terminate

Error: Forbidden
Response body
{
  "message": "invalid csrf token"
}
Response headers
 content-length: 33 
 content-type: application/json; charset=UTF-8 
 date: Mon, 29 Aug 2022 09:13:01 GMT 
 vary: Origin 
 x-content-type-options: nosniff 
 x-frame-options: SAMEORIGIN 
 x-xss-protection: 1; mode=block 

**What is the cause of this error？**
**Or how to delete in Java**

**Comment by Tarang** [comment]
Ive deployed via kubernetes using a helm chart. So there is a `temporal-web` service in my cluster.

I have an internal NLB attached that exposes the endpoint more broadly, so that it does not need `kubectl port-forward` to access it.

If I was to use kubernetes to access it via `kubectl port-forward` and terminate a workflow on my localhost:8080, it will work.

However if i use the endpoint that exposes the service to access temporal-web, i can view the temporal web ui fine and it contains all the data. However if i try to terminate a workflow using the button in the ui it will throw me off to a 404 page.

Further investigation reveals the call to `POST` `.../terminate` returns `{"message":"invalid csrf token"}` with status code 403. The browser subsequently returns a 404.

The expected behaviour would be both:
- The workflow terminates successfully,
- If it does not terminate an error is shown with the reason (instead of a 404)

**Comment by Tarang** [comment]
In addition to the terminate workflow button, the 'view stack trace' also does not behave well and says there are no workers attached. However with `kubectl port-forward` mode it works fine.

**Comment by StarpTech** [comment]
What's the status? I also run into "invalid csrf token".

**Comment by OmarSultan85** [comment]
We are facing the exact same issue on Kubernetes

**Comment by jaeholee2212** [comment]
+1

**Comment by cyzhzhd** [comment]
+1

**Comment by OmarSultan85** [comment]
Hey any update on this issue?

**Comment by bendres97** [comment]
I've also replicated this error with docker on 2.6.1 and up when trying to create a schedule. The only way that I'm able to create schedules or terminate workflows without getting an "Invalid CSRF Token" error is if I proxy my traffic through the host server to access via localhost. I presumed that I need to configure the web ui with the domain name of the server but I cannot find a setting regardless of where I search. I've also tried forwarding various HTTP headers without success. This is a pretty large problem affecting multiple versions - I'm very surprised this hasn't been identified and rectified by now.

**Comment by philous** [comment]
+1

**Comment by bendres97** [comment]
Okay I found a better(ish) workaround for this. If you stick a proxy in front of this so that you can use HTTPS it should work. I found that my browser is throwing out the CSRF cookie because I wasn't using a secure connection. Adding a proxy isn't exactly trivial but I already had a proxy setup for other services I'm running. So I guess there's two approaches here:

Add option to disable CSRF entirely or not run on HTTP connections
Add an HTTPS frontend to the Web UI (I haven't checked the documentation to see if this is already an option)

**Comment by OmarSultan85** [comment]
Is there any update on this?

**Comment by wilsoniya** [comment]
Looks like the `SetCookie` response header is being sent with the `Secure` attribute set, e.g.: 

```
_csrf=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; Path=/; Expires=Thu, 26 Jan 2023 18:20:16 GMT; Secure; SameSite=Strict
```

It would be nice if this was configurable.

**Comment by Giftia** [comment]
An effective interim remedy is to set the cookie to `_csrf=${csrf_token_got_from_Set-Cookie_header}`.

![image](https://user-images.githubusercontent.com/12429652/218618022-728830b7-cfaa-4190-ba73-fb2b5b9480a7.png)

![image](https://user-images.githubusercontent.com/12429652/218618131-89eafafe-662e-42e3-9b41-ef634b1151e6.png)

And it works like this:

![image](https://user-images.githubusercontent.com/12429652/218618182-0e1cc28e-a779-4f79-ad07-ba1816aa01aa.png)

**Comment by feedmeapples** [comment]
we've added an option to pass cookie insecurely https://github.com/temporalio/ui/blob/71ba8d3b02780ca507268c37daf33861eddc0047/server/docker/config_template.yaml#LL20C5-L20C5 

For context, when these conditions meet:
 - UI is hosted non-localhost
 - UI is served over HTTP (not HTTPS)
 - secure cookie is enabled
 
browsers will drop passing the cookie with CSRF token in Temporal UI. To address this either add a reverse proxy / expose over HTTPS or disable secure cookie in UI config (depending on your security practices)
