### ISSUE TITLE
Refresh button on detail page

### ISSUE THREAD

**Issue by skandragon** [temporalio/ui#862]
## Is your feature request related to a problem? Please describe.

Jumping back to the main page to reload, or using force-reload in the browser, to get updated details is a pain.

## Describe the solution you'd like

It would be nice, when looking at the workflow execution details, if it would provide a refresh button similar to what is on the main page.  This prevents having to jump around to get up to date info on currently running tasks.

An auto-refresh when not "completed" may be nice too...

## Describe alternatives you've considered

None.

## Additional context

None.

**Comment by aakarim** [comment]
Totally agree with this. I like to keep tabs (haha) on 1-5 hour long running tasks that have many failure paths. An auto-refresh on the detail page (and on the workflows page too) would be really helpful here.

This was what I missed the most when I moved from Argo workflows over to Temporal.

**Comment by Alex-Tideman** [comment]
What would your preferred auto-refresh interval be? One minute?

**Comment by tomwheeler** [comment]
I'll add that the auto-refresh feature would be especially helpful during live demos where you're trying to show retries, since this currently requires refreshing the page to see each new attempt. 

I don't know if it's feasible or not, but it would be incredible if the detail page for a given Workflow Execution refreshed automatically after each retry attempt or new history event (however, I could also see how someone trying to trace the history might find this annoying, so maybe a checkbox to toggle auto-refresh would be helpful).

**Comment by aakarim** [comment]
> What would your preferred auto-refresh interval be? One minute?
I'd expect the default to be 5 or 10s. I could imagine getting pretty frustrated starting at the screen for a minute waiting for it to refresh.

The Grafana dashboard refresh feature also has a dropdown with configurable interval, something like this would be a nice-to-have. 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/3791557/196206377-f8e2f4b6-761b-4de8-b63b-0343492c5882.png">
