### ISSUE TITLE
Clarifying relationship of repo tags to docker tags?

### ISSUE THREAD

**Issue by deltamualpha** [temporalio/ui#974]
This isn't really a bug or a feature request, just something I find confusing:

What is the relationship between tags/releases in this repo and tags on the docker image?

<https://hub.docker.com/r/temporalio/ui/tags> lists the latest (as of this writing) docker tag as `2.9.0`. The latest tag on this repo is [`v2.1.88`](https://github.com/temporalio/ui/releases/tag/v2.1.88).

Obviously, one way to solve this problem is to not worry about it and just pull `:latest` all the time for the UI, but if you're running multiple nodes in a cluster, new nodes might pull a fresher version that existing ones and you'll get 404s as each node's JS tries to load from other older/newer nodes.

**Comment by Alex-Tideman** [comment]
Hey @deltamualpha, thanks for asking!

The docker tag (`2.9.0`) refers to the ui-server version (which includes ui-server and ui repos).

The releases in this repo are for managing our NPM package versions of `@temporalio/ui`. We wanted to start documenting the changelog of our package versions and so that's what those releases communicate.
